#!/usr/bin/env python
# -*- coding: utf-8 -*-

LIMITE_INF = 3
LIMITE_SUP = 10
TEMP_MIN = -20
TEMP_MAX = 100
LUMINOSIDAD_MIN = 0
LUMINOSIDAD_MAX = 100
HUMEDAD_MIN = 0
HUMEDAD_MAX = 100
ITERACIONES_MAX = 20
